# -*- coding: utf-8 -*-
"""modeling_gunung

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WgRx6qhRsJfC9L7rPCE1UKcTGGFW6Unk
"""

# ===============================
# 1️⃣ Import Library
# ===============================
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity
import joblib
import tensorflow as tf
from tensorflow.keras import layers, models

# ===============================
# 2️⃣ Load Dataset
# ===============================
df = pd.read_csv("dataset_gunung_final.csv")

# ===============================
# 3️⃣ Preprocessing
# ===============================
# Encode categorical
le_diff = LabelEncoder()
df['difficulty_encoded'] = le_diff.fit_transform(df['difficulty_level'])

le_level = LabelEncoder()
df['level_encoded'] = le_level.fit_transform(df['recommended_for'])

# Scaling numeric
scaler = MinMaxScaler()
df[['elevation_scaled','duration_scaled','distance_scaled','gain_scaled']] = scaler.fit_transform(
    df[['elevation_m','hiking_duration_hours','distance_km','Elevation_gain']]
)

# ===============================
# 4️⃣ Simpan Preprocessing Model
# ===============================
joblib.dump(le_diff, "le_diff.pkl")
joblib.dump(le_level, "le_level.pkl")
joblib.dump(scaler, "scaler.pkl")

# ===============================
# 5️⃣ Content-Based Filtering Function
# ===============================
def content_based_recommendation(user_input, df, top_n=5):
    """
    user_input: dict dengan keys
        'elevation_m', 'hiking_duration_hours', 'distance_km', 'Elevation_gain',
        'difficulty_level', 'recommended_for'
    df: dataset gunung sudah preprocessed
    top_n: jumlah rekomendasi
    """
    # Transform user input sama seperti preprocessing dataset
    user_scaled = scaler.transform([[user_input['elevation_m'],
                                     user_input['hiking_duration_hours'],
                                     user_input['distance_km'],
                                     user_input['Elevation_gain']]])[0]

    user_vector = np.array([[
        user_scaled[0],  # elevation_scaled
        user_scaled[1],  # duration_scaled
        user_scaled[2],  # distance_scaled
        user_scaled[3],  # gain_scaled
        le_diff.transform([user_input['difficulty_level']])[0],
        le_level.transform([user_input['recommended_for']])[0]
    ]])

    features = ['elevation_scaled','duration_scaled','distance_scaled','gain_scaled','difficulty_encoded','level_encoded']

    similarity = cosine_similarity(user_vector, df[features])

    # Jangan overwrite df asli, buat salinan untuk safety
    df_result = df.copy()
    df_result['similarity'] = similarity[0]

    top_gunung = df_result.sort_values('similarity', ascending=False).head(top_n)
    return top_gunung

# ===============================
# 6️⃣ Contoh Panggilan Fungsi CBF
# ===============================
user_input_example = {
    'elevation_m': df['elevation_m'].median(),
    'hiking_duration_hours': 5,
    'distance_km': 10,
    'Elevation_gain': df['Elevation_gain'].median(),
    'difficulty_level': 'Moderate',
    'recommended_for': 'Intermediate'
}

top_gunung = content_based_recommendation(user_input_example, df, top_n=5)

print(top_gunung[['Name','similarity']])

# ===============================
# 7️⃣ (Opsional) MLP Ranking
# ===============================
features = ['elevation_scaled','duration_scaled','distance_scaled','gain_scaled','difficulty_encoded','level_encoded']
X = df[features]
y = content_based_recommendation(user_input_example, df, top_n=len(df))['similarity']  # gunakan similarity sebagai target dummy

mlp_model = models.Sequential([
    layers.Input(shape=(len(features),)),
    layers.Dense(32, activation='relu'),
    layers.Dense(16, activation='relu'),
    layers.Dense(1, activation='linear')
])

mlp_model.compile(optimizer='adam', loss='mse')
mlp_model.fit(X, y, epochs=50, batch_size=4)

# ===============================
# 8️⃣ Save MLP Model
# ===============================
mlp_model.save("mlp_model_gunung.h5")

# ===============================
# 9️⃣ Simpan Dataset Preprocessed (opsional)
# ===============================
df.to_csv("dataset_gunung_preprocessed.csv", index=False)